### ISSUE TITLE
Update texstudio to 2.11.2

### ISSUE THREAD

**Issue by koppor** [aronovgj/choco-auto#11]
Texstudio 2.11.2 was [released yesterday](http://www.texstudio.org/#news) and it should be updated.

On https://chocolatey.org/packages/texstudio the link to the source package points to https://github.com/BenjaminHae/choco-packages, which is not active any more (https://github.com/BenjaminHae/choco-packages/issues/3#issuecomment-250370280). Can the link be updated to https://github.com/aronovgj/choco-auto/tree/master/texstudio?

**Comment by aronovgj** [comment]
https://chocolatey.org/packages/texstudio/2.11.2

**Comment by aronovgj** [comment]
Thought I fixed that a long time ago...

**Comment by aronovgj** [comment]
Thats now fixed. Thanks
