### ISSUE TITLE
Choco install miktex returns 404 everytime I try to install

### ISSUE THREAD

**Issue by eyenir** [aronovgj/choco-auto#12]
Hi,

I tried installing the package but I get the following output:

`C:\WINDOWS\system32>chocolatey install miktex
Chocolatey v0.10.3
Installing the following packages:
miktex
By installing you accept licenses for the packages.

miktex v2.9.6069.3 [Approved]
miktex package files install completed. Performing other installation steps.
The package miktex wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting
 'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
Do you want to run the script?([Y]es/[N]o/[P]rint): y

Sorry for the package fixes, just trying to get AutoInstall=1 right.
Attempt to get headers for http://latex.imamu.edu.sa/tex-archive/systems/win32/miktex/setup/basic-miktex-x64.exe failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://latex.imamu.edu.sa/tex-archive/systems/win32/miktex/setup/basic-miktex-x64.exe'. Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the remote server"
Downloading miktex 64 bit
  from 'http://latex.imamu.edu.sa/tex-archive/systems/win32/miktex/setup/basic-miktex-x64.exe'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://latex.imamu.edu.sa/tex-archive/systems/win32/miktex/setup/basic-miktex-x64.exe'. Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the remote server"
This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.
The install of miktex was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\miktex\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
- miktex (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\miktex\tools\chocolateyInstall.ps1'.
  See log for details.`

As far as I see the package doesn't supply a valid mirror for miktex (at least for my country). Please update it.

**Comment by aronovgj** [comment]
The install script forwards you to a download URL that CTAN thinks is best for you. Sometimes it happens that you are forwarded to a non-working URL. As the URL works for me, I can conclude that it was either temporarily down or that your country or your company or whatever in fact blocks the URL. Could you see if http://latex.imamu.edu.sa/tex-archive/systems/win32/miktex/setup/basic-miktex-x64.exe works for you now? I could try to add fallback URLs to the script in the next versions.

**Comment by aronovgj** [comment]
Also it may happen that you are forwarded to a different URL next time you try to `choco install` it

**Comment by eyenir** [comment]
Again not working. what do you mean by `choco install`? isn't it the same like `chocolatey install`? As a side-remark the script in Miktex's site refered me successfully to a working mirror in Iran (http://ctan.asis.io/systems/win32/miktex/setup/basic-miktex-2.9.6069-x64.exe) rather than to the link in CTAN. Maybe you can fetch the file like them by detecting users' locations (say by ip address) instead of using the mirrors link?

**Comment by aronovgj** [comment]
It already does find a URL based on your location as far as I see. It asks CTAN to be forwarded and CTAN tries to figure out where you are from. That's why the download link is from Saudi Arabia and not an American/East Asian/European URL. Though I guess it does not consider political circumstances. 
`choco install` and `chocolatey install` should be the same. Not sure what I could do to solve this for you.

**Comment by eyenir** [comment]
Currently CTAN is supposed to locate the use for you. As you can see, not always it succeeds. Why not to add an optional parameter (say `-a` for an address) for a custom repository supplied by the user. In my case seems like calling a command like `choco install miktex -a http://ctan.asis.io/systems/win32/miktex/setup/basic-miktex-2.9.6069-x64.exe` can be useful. Another option (clumsy and lazy, I admit) is to fetch the link from miktex's site (In python that's few lines after importing `BubbleSoap`). Anyways, the use of CTAN appears to prevent users of installing MikTeX, LyX etc by using choco....

**Comment by aronovgj** [comment]
Kind of would defeat the purpose of having a URL in the install script. But I'd accept a pull request.

**Comment by aronovgj** [comment]
Oh, and no python please. Don't want to have unnecessary dependencies.

**Comment by eyenir** [comment]
I know but there's no need to punish people from Middle East (we have ISIS exactly for this purpose I guess). I've never submitted a pull-request so it may take me a day or so. Thanks once again. Python is great but as you wish...

**Comment by aronovgj** [comment]
I'm not punishing anyone. I couldn't care less who uses miktex. Complaints should go to CTAN, your government oder Saudi Arabia. 

If I add Python as a dependency people will start complaining about that because PowerShell can probably do the same.

**Comment by eyenir** [comment]
I didn't mean to complain and I apologize if I was misunderstood. I opened a pull-request. It's the first time I'm coding PS so please go over it attentively. Thanks once again.
