### ISSUE TITLE
Unneccessary win 10/7 split packages for geforce

### ISSUE THREAD

**Issue by AeliusSaionji** [aronovgj/choco-auto#14]
https://github.com/aronovgj/choco-auto/commit/ae11d6c1a129ece1fab59b2030c3274bcefee220

Yes, ketarin wasn't the best tool, which is why chocolaty maintainers should be migrating to AU https://github.com/majkinetor/au

**Comment by AeliusSaionji** [comment]
Take your time to learn AU (I've certainly been dragging my feet about it) and reintegrate the packages when you're able.

**Comment by aronovgj** [comment]
I'm not planning to learn au until it is Linux compatible. However, I am always happy if someone else wants to maintain my packages.

**Comment by aronovgj** [comment]
I switched to AMD. Someone will have to take over this package as I can not debug it anymore.
