### ISSUE TITLE
Malwarebytes checksum is wrong

### ISSUE THREAD

**Issue by RedBaron2** [aronovgj/choco-auto#20]
Dear aronovgj,
The checksum that you have for the current package of Malwarebytes does not match.
The old checksum was 'b230dd46fb7238f41c80ea7053cee51f9bb14dbc8ba1775e2364c2c3e12d5482'
The New checksum is 'af82ad5b965d05b82cac137d586d06bfa85988bf830cc61591e7a79b917a94fc'

Thanks for the package, and enjoy the weekend 😄

**Comment by aronovgj** [comment]
Yes, that's a thing lately. They seem to have changed how they version or release new versions. The current one is `3.1.2.1733-1.0.122-1.0.1976` which I cannot use in chocolatey. I'll try and think of something.

**Comment by aronovgj** [comment]
Let's hope they don't change the installer while keeping the file name the same. Else I would not be able to keep the package up to date.
https://chocolatey.org/packages/malwarebytes/3.1.2.1733101976

Please reopen if the checksums don't match. (Wait a day though before you do, new packages are pushed only when my PC is running)

**Comment by RedBaron2** [comment]
@aronovgj 
Thanks for the checksum fix. Greatly Appreciated 😄
